var imglib = [
{
	"sheetname"				: "playersheet",
	"type"					: "player",
	"src"					: "library/playersheet.png",
	"width"					: 108,
	"height"				: 192,
	"framewidth"			: 36,
	"frameheight"			: 48,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "racersheet",
	"type"					: "racer",
	"src"					: "library/racersheet.png",
	"width"					: 108,
	"height"				: 48,
	"framewidth"			: 36,
	"frameheight"			: 48,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "choppersheet",
	"type"					: "chopper",
	"src"					: "library/choppersheet.png",
	"width"					: 128,
	"height"				: 64,
	"framewidth"			: 64,
	"frameheight"			: 64,
	"framedelay"			: 1,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "carsheet",
	"type"					: "car",
	"src"					: "library/carsheet.png",
	"width"					: 144,
	"height"				: 704,
	"framewidth"			: 48,
	"frameheight"			: 64,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "alertsheet",
	"type"					: "alerter",
	"src"					: "library/alert.gif",
	"width"					: 64,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "playershadow",
	"type"					: "playershadow",
	"src"					: "library/playershadow.png",
	"width"					: 72,
	"height"				: 48,
	"framewidth"			: 36,
	"frameheight"			: 48,
	"framedelay"			: 1,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "monstersheet",
	"type"					: "monster",
	"src"					: "library/monstersheet.png",
	"width"					: 256,
	"height"				: 128,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "numberssheet",
	"type"					: "numbers",
	"src"					: "library/numbers.png",
	"width"					: 240,
	"height"				: 48,
	"framewidth"			: 24,
	"frameheight"			: 48,
	"framedelay"			: 0,
	"framesperdirection"	: 0,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "explosionsheet",
	"type"					: "explosion",
	"src"					: "library/explosion.png",
	"width"					: 384,
	"height"				: 64,
	"framewidth"			: 64,
	"frameheight"			: 64,
	"framedelay"			: 4,
	"framesperdirection"	: 6,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "playermissilesheet",
	"type"					: "playermissile",
	"src"					: "library/playermissile.png",
	"width"					: 8,
	"height"				: 64,
	"framewidth"			: 8,
	"frameheight"			: 32,
	"framedelay"			: 0,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "entitysheet",
	"type"					: "entity",
	"src"					: "library/entities.png",
	"width"					: 64,
	"height"				: 256,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "tilesheet",
	"type"					: "tile",
	"src"					: "library/tilesheet.png",
	"width"					: 48,
	"height"				: 192,
	"framewidth"			: 48,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "alienbomb",
	"type"					: "alienbomb",
	"src"					: "library/alienbomb.png",
	"width"					: 24,
	"height"				: 48,
	"framewidth"			: 24,
	"frameheight"			: 24,
	"framedelay"			: 4,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "groundsheet",
	"type"					: "road",
	"src"					: "library/groundsheet.png",
	"width"					: 320,
	"height"				: 288,
	"framewidth"			: 320,
	"frameheight"			: 48,
	"framedelay"			: 0,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "fringesheet",
	"type"					: "fringe",
	"src"					: "library/fringesheet.png",
	"width"					: 24,
	"height"				: 288,
	"framewidth"			: 24,
	"frameheight"			: 48,
	"framedelay"			: 0,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "shardssheet",
	"type"					: "shards",
	"src"					: "library/shards.png",
	"width"					: 16,
	"height"				: 64,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 1,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
}
];